---
# tasks file for server_security role

- name: Security | Execute package updates and cleanup
  ansible.builtin.import_tasks: apt.yml
  when:
    - ansible_os_family == 'Debian'
  tags:
    - security
    - apt
    - update-only

- name: Security | Set system timezone
  become: true
  community.general.timezone:
    name: "{{ server_security_timezone }}"
  tags:
    - security
    - timezone

- name: Security | Configure hostname
  ansible.builtin.import_tasks: set_hostname.yml
  when: "'set_hostname' in server_security_tasks"
  tags:
    - security
    - hostname

- name: Security | Apply pending handlers before continuing
  ansible.builtin.meta: flush_handlers

- name: Security | Configure SSH security
  ansible.builtin.import_tasks: ssh.yml
  when:
    - ansible_os_family == 'Debian'
    - "'ssh_security' in server_security_tasks"
    - ansible_distribution_version != "22.10"
    - ansible_distribution_major_version|int <= 22
  tags:
    - security
    - ssh

- name: Security | Setup backup routines
  ansible.builtin.import_tasks: backup.yml
  when: "'backup' in server_security_tasks"
  tags:
    - security
    - backup

- name: Security | Configure LUKS auto-unlock
  ansible.builtin.include_tasks: auto_unlock.yml
  loop: "{{ server_security_auto_unlocks | default([]) }}"
  loop_control:
    loop_var: auto_unlock_drive
    index_var: loop_idx
  vars:
    auto_unlock_target_crypt_counter: "{{ loop_idx }}"
    auto_unlock_encrypted_drive_identifier: "{{ auto_unlock_drive.name }}"
    auto_unlock_encrypted_drive_mount_point: "{{ auto_unlock_drive.auto_unlock_encrypted_drive_mount_point }}"
    auto_unlock_secret_name: "{{ auto_unlock_drive.auto_unlock_secret_name }}"
  when:
    - "'auto_unlock' in server_security_tasks"
    - server_security_auto_unlocks is defined
    - server_security_auto_unlocks | length > 0
  tags:
    - security
    - luks
    - auto-unlock
