---
# handlers file for server_security role

- name: Restart ssh
  become: true
  ansible.builtin.systemd:
    name: "{{ 'ssh' if ansible_distribution == 'Ubuntu' else 'sshd' }}"
    state: restarted
    daemon_reload: true

- name: Restart server
  become: true
  ansible.builtin.reboot:
    msg: "Ansible triggered reboot for security updates"
    reboot_timeout: 600
    pre_reboot_delay: 5
    post_reboot_delay: 30

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart fail2ban
  become: true
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: true

- name: Restart ufw
  become: true
  ansible.builtin.systemd:
    name: ufw
    state: restarted
    enabled: true
